package main

import (
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/tmaxmax/go-sse"
)

func main() {
	s := &sse.Server{}

	// creating fake sse events
	go func() {
		m := &sse.Message{}
		m.AppendData("Hello World")

		for range time.Tick(time.Second) {
			_ = s.Publish(m)
		}
	}()

	// serving html auto-generated by vite
	http.Handle("/", http.FileServer(http.Dir("../client/src/dist")))

	// set a specific endpoint for "/sse" to recieve emits from js code
	http.Handle("/sse", s)

	fmt.Println("go server is ready to run on port 8000")
	if err := http.ListenAndServe(":8000", nil); err != nil {
		log.Fatalln(err)
	}
}
